#ifndef ENUM_DUEL_MODE_HPP
#define ENUM_DUEL_MODE_HPP

#define DUEL_TEST_MODE         0x01
#define DUEL_ATTACK_FIRST_TURN 0x02
//#define DUEL_NO_CHAIN_HINT     0x04
#define DUEL_OBSOLETE_RULING   0x08
#define DUEL_PSEUDO_SHUFFLE    0x10
#define DUEL_TAG               0x20
#define DUEL_SIMPLE_AI         0x40
#define DUEL_SPEED             0x80
#define DUEL_OBSOLETE_IGNITION 0x100
#define DUEL_1ST_TURN_DRAW     0x200
#define DUEL_1_FIELD           0x400
#define DUEL_PZONE             0x800
#define DUEL_SEPARATE_PZONE    0x1000
#define DUEL_EMZONE            0x2000
#define DUEL_RELAY             0x4000
#define DUEL_MODE_MR1          (DUEL_OBSOLETE_IGNITION + DUEL_1ST_TURN_DRAW + DUEL_1_FIELD)
#define DUEL_MODE_MR2          (DUEL_1ST_TURN_DRAW + DUEL_1_FIELD)
#define DUEL_MODE_MR3          (DUEL_PZONE + DUEL_SEPARATE_PZONE)
#define DUEL_MODE_MR4          (DUEL_PZONE + DUEL_EMZONE)
#define DUEL_MODE_MR1_FORB     (TYPE_XYZ + TYPE_PENDULUM + TYPE_LINK)
#define DUEL_MODE_MR2_FORB     (TYPE_PENDULUM + TYPE_LINK)
#define DUEL_MODE_MR3_FORB     TYPE_LINK
#define DUEL_MODE_MR4_FORB     0

#endif // ENUM_DUEL_MODE_HPP
